namespace drdog_minion
{
    enum Sprites
    {
      drdog_minion_attackc1 = 0,
      drdog_minion_attackc2,
      drdog_minion_attackc3,
      drdog_minion_attackc4,
      drdog_minion_attackc5,
      drdog_minion_attackc6,
      drdog_minion_attacks1,
      drdog_minion_attacks2,
      drdog_minion_attacks3,
      drdog_minion_attacks4,
      drdog_minion_attacks5,
      drdog_minion_attacks6,
      drdog_minion_climb1,
      drdog_minion_climb2,
      drdog_minion_climb3,
      drdog_minion_climbs1,
      drdog_minion_climbs2,
      drdog_minion_climbs3,
      drdog_minion_death1,
      drdog_minion_death2,
      drdog_minion_death3,
      drdog_minion_death4,
      drdog_minion_death5,
      drdog_minion_death6,
      drdog_minion_death7,
      drdog_minion_death8,
      drdog_minion_death9,
      drdog_minion_death10,
      drdog_minion_jump,
      drdog_minion_jumpg,
      drdog_minion_pickup1,
      drdog_minion_pickup2,
      drdog_minion_pickup3,
      drdog_minion_walk1,
      drdog_minion_walk2,
      drdog_minion_walk3,
      drdog_minion_walkg1,
      drdog_minion_walkg2,
      drdog_minion_walkg3,
    };
}

